In [27]:
import torch

command
- torch.emtry(dim1,dim2,......)

In [2]:
print(torch.empty(1)) # tensor 1 dim 
print(torch.empty(1,2)) # tensor matrix row and column
print(torch.empty(4,2)) # tensor matrix row and column
print(torch.empty(2,4,3)) # mini-batch,row,columns


tensor([0.])
tensor([[0., 0.]])
tensor([[2.6884e-23, 1.6689e-42],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])
tensor([[[2.6884e-23, 1.6689e-42, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


command   
- torch.rand() range 0,1
- torch.zeros() like numpy   
- torch.ones()

In [3]:
print(torch.rand(3,3)) # 0 - 1
print(torch.zeros(3,3))
print(torch.ones(3,3))

tensor([[0.5233, 0.2418, 0.7467],
        [0.0293, 0.6274, 0.0030],
        [0.9113, 0.8267, 0.7815]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


command
- data type check

In [7]:
x = torch.ones(3,3)
print(x) 
print(x.dtype) # default float32

# we can also give it the following parameter ourselves.
y = torch.ones(3,3 , dtype=torch.int)
print(y)

z = torch.zeros(3,3 , dtype=torch.double)
print(z)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


command 
- size
- operation

In [12]:
x = torch.tensor([[1,2]])
print(x)
print(x.size())

tensor([[1, 2]])
torch.Size([1, 2])


In [16]:
x = torch.tensor([[1,2,3]])
y = torch.tensor([[1,2,3]])
print(x+y) # these the same thing 
print(torch.add(x,y)) # minus sub , multipication mul , division div 

tensor([[2, 4, 6]])
tensor([[2, 4, 6]])


command 
- slicing operation 

In [28]:
x = torch.rand(5,3)
display(x)
display(x[:,0]) #all the rows but 1 columns

tensor([[0.8070, 0.4347, 0.7509],
        [0.4814, 0.6699, 0.2964],
        [0.9158, 0.5852, 0.9932],
        [0.4565, 0.1974, 0.2407],
        [0.4006, 0.4363, 0.5459]])

tensor([0.8070, 0.4814, 0.9158, 0.4565, 0.4006])

In [34]:
print(x[1,1]) #dim reduct 
print(x[1,1].item()) #actual value, be careful must 1 element only

tensor(0.6699)
0.6698572039604187


command 
- resize

In [47]:
x = torch.rand(4,4)
print(x.size())
print(x.view(-1).size())
print(x.view(-1)) # break down 
print(x.view(-1,8)) # break down division 2 
#view same reshape

torch.Size([4, 4])
torch.Size([16])
tensor([0.0977, 0.1722, 0.2892, 0.9402, 0.8495, 0.3541, 0.1562, 0.6388, 0.8129,
        0.0817, 0.2989, 0.6352, 0.2506, 0.1063, 0.3331, 0.3600])
tensor([[0.0977, 0.1722, 0.2892, 0.9402, 0.8495, 0.3541, 0.1562, 0.6388],
        [0.8129, 0.0817, 0.2989, 0.6352, 0.2506, 0.1063, 0.3331, 0.3600]])


command 
- change numpy to tensor 
- change tensor to numpy 

In [61]:
import numpy as np
x = np.ones(5) # numpy 
print(x) #array
y = torch.from_numpy(x)
print(y)
z = torch.tensor(x)
print(z)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [63]:
x = torch.ones(5)
print(x)
y = x.numpy()
print(y)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [ ]:
# be careful here 
x = torch.ones(5)
print(x)
y = x.numpy()
print(y)
z = x.add_(1)
print(z) # same memory but GPU not happend 
print(y)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [69]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    print(torch.cuda.get_device_name(0))
    z = torch.tensor([[1]]).to(device=device)
    print(z)

NVIDIA GeForce RTX 3060 Laptop GPU
tensor([[1]], device='cuda:0')
