In [17]:
import numpy as np

In [3]:
import torch

w = torch.tensor(1.0,requires_grad=True)
x = torch.tensor(1.0)
y = torch.tensor(2.0)

y_hat = w * x
loss = (y_hat - y)**2
# dL/dw = 2(wx-y)x
# take value = 2(1-2)1 = -2

# forward 
print(loss)

#backward 
loss.backward()
print(w.grad)



tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


In [44]:
import torch


X = torch.tensor([1,2,3,4],dtype=torch.float32)
Y = torch.tensor([2,4,6,8],dtype=torch.float32)
w = torch.tensor(0.0,requires_grad=True,dtype=torch.float32)

#f = wx

def forward(x):
    return w*x

def loss(y_predicted,y):
    return ((y_predicted - y)**2).mean()


#grdient descent 
learning_rate = 0.1
n_iters = 10

for epoch in range(n_iters):
    # forward pass 
    y_pred = forward(X)
    l = loss(y_pred,Y)
    
    # backward pass 
    l.backward()

    #update 
    with torch.no_grad(): #stop add node
        w -= learning_rate*w.grad


    w.grad.zero_()
    print(f'epoch {epoch+1} MSE {l:.4}')
    print(y_pred)
    print(Y)
    print("*"*50)



epoch 1 MSE 30.0
tensor([0., 0., 0., 0.], grad_fn=<MulBackward0>)
tensor([2., 4., 6., 8.])
**************************************************
epoch 2 MSE 7.5
tensor([ 3.,  6.,  9., 12.], grad_fn=<MulBackward0>)
tensor([2., 4., 6., 8.])
**************************************************
epoch 3 MSE 1.875
tensor([1.5000, 3.0000, 4.5000, 6.0000], grad_fn=<MulBackward0>)
tensor([2., 4., 6., 8.])
**************************************************
epoch 4 MSE 0.4688
tensor([2.2500, 4.5000, 6.7500, 9.0000], grad_fn=<MulBackward0>)
tensor([2., 4., 6., 8.])
**************************************************
epoch 5 MSE 0.1172
tensor([1.8750, 3.7500, 5.6250, 7.5000], grad_fn=<MulBackward0>)
tensor([2., 4., 6., 8.])
**************************************************
epoch 6 MSE 0.0293
tensor([2.0625, 4.1250, 6.1875, 8.2500], grad_fn=<MulBackward0>)
tensor([2., 4., 6., 8.])
**************************************************
epoch 7 MSE 0.007324
tensor([1.9688, 3.9375, 5.9062, 7.8750], grad_fn=<Mul